# Generated by Django 3.2.3 on 2021-07-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('fono', models.IntegerField(verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('email', models.CharField(max_length=60, verbose_name='Email')),
                ('pais', models.CharField(max_length=60, verbose_name='País')),
                ('password', models.CharField(max_length=60, verbose_name='Contraseña')),
            ],
        ),
    ]
